accesslog = "-"
alt_svc_headers = ["h3=\":443\"; ma=3600, h3-29=\":443\"; ma=3600"]
bind = "0.0.0.0:8443"
certfile = "/cert/pgjones.dev.crt"
errorlog = "-"
insecure_bind = "0.0.0.0:8080"
keyfile = "/cert/pgjones.dev.key"
server_names = ["pgjones.dev"]
quic_bind = "0.0.0.0:4433"
worker_class = "trio"
