date = "2019-10-09"
id = "early-look-at-http3-2019"
summary = "This is an overview of how this site performs when served over HTTP/3."
title = "An early look at HTTP/3"
body = """
# An early look at HTTP/3

##### 2019-10-19

HTTP/3 is the next generation HTTP version that is currently being
standardised and developed. Happily that development is now at a stage
whereby there is initial browser and server support. This allows for
HTTP/3 to be compared against HTTP/2 and HTTP/1. Note though that is
just for fun, it is too early to draw meaningful conclusions.

This site is served over HTTP/1, 2, and 3, as described in [this blog
post](https://pgjones.dev/blog/http-1-2-3-2019/), so it will be
used. However this site only partially represents "modern" sites - it
is too small.

To use a HTTP/3 supporting browser,

```shell
Google\\ Chrome\\ Canary --enable-quic --quic-version=h3-23
```

to use a HTTP/1.1 only browser (disable HTTP/2),

```shell
Google\\ Chrome\\ Canary --disable-http2
```

to use a HTTP/2 browser (Chrome will by default use HTTP/2 over HTTP/1),
```shell
Google\\ Chrome\\ Canary
```

note I'm using Chrome `79.0.3937.0`.

Then we can visit this site and view the loading waterfall, a protocol
value of `http/2+quic/99` indicates the request was served over
HTTP/3. The results I see are given below (note I disabled server
push when I recorded these),

### HTTP/1.1

![This site served over HTTP/1.1](https://pgjones.dev/static/img/h11.png)

### HTTP/2

![This site served over HTTP/2](https://pgjones.dev/static/img/h2.png)

### HTTP/3

![This site served over HTTP/3](https://pgjones.dev/static/img/h3.png)

## In comparison

I expected HTTP/2 to be slightly quicker than HTTP/1.1 (this site has
too few resources to make a large difference). I also expected HTTP/3
to be comparable rather than take almost three times longer. However
this is too early in the development process to draw any conclusions
on performance differences (this does serve as a marker I can compare
against when HTTP/3 goes mainstream though). What is good though is
that HTTP/3 works, and if I hadn't been looking I wouldn't have known
it was served using HTTP/3.

"""
