date = "2019-09-03"
id = "rss-feed-2019"
summary = """
RSS is very useful feature that was missing from this blog, so I've
added it. This explains why I've added it and how.
"""
title = "Adding an RSS feed"

body = """
A recent [blog
post](https://kevq.uk/please-add-rss-support-to-your-site) and a
twitter request has made me rethink RSS support for this blog. I had
believed that RSS was unused, but I now think it is in the mist of a
revival. So now you can follow this blog via this [atom
feed](https://pgjones.dev/blog/atom.xml) or this [rss
feed](https://pgjones.dev/blog/rss20.xml).

# Implementation

This is the
[commit](https://gitlab.com/pgjones/pgjones_dev/commit/feb10bc29514caa9a2eeffd2285360e841e64c98)
that adds RSS support. It works using the
[Python-Feedgen](https://github.com/lkiesow/python-feedgen)
library. At startup the blog posts are loaded and converted into an
atom and a rss feed,

```python
@app.before_serving
async def create_feeds():
    feed = FeedGenerator()
    feed.title("PGJones' blog")
    feed.author({"name": "PGJones", "email": "philip.graham.jones@googlemail.com"})
    feed.logo("https://pgjones.dev/static/media/MeSudbury.bd83a6a4.jpeg")
    feed.link(href="https://pgjones.dev/blog/", rel="alternate")
    feed.link(href="https://pgjones.dev/blog/feed.atom", rel="self")
    feed.language("en")
    feed.id("https://pgjones.dev/blog/")
    feed.description("Blog posts from PGJones")
    for blog in _load_blogs():
        entry = feed.add_entry()
        entry.id(f"https://pgjones.dev/blog/{blog['id']}/")
        entry.link(href=f"https://pgjones.dev/blog/{blog['id']}/")
        entry.title(blog["title"])
        entry.summary(blog["summary"])
        published = datetime.combine(date.fromisoformat(blog["date"]), datetime.min.time())
        entry.published(published.astimezone(timezone.utc))
    app.feeds = (feed.rss_str(), feed.atom_str())
```

these are then served as you'd serve anything else,

```python
@app.route("/blog/atom.xml")
async def atom_feed():
    return app.feeds[1], {"Content-Type": "text/xml"}


@app.route("/blog/rss20.xml")
async def rss_feed():
    return app.feeds[0], {"Content-Type": "text/xml"}
```

I hope they help :).
"""
